"""Software updates: signed bundles, the GitHub release check, and the applier.

A Marquee update is a single `.mqup` file — an uncompressed tar holding
`payload.tar.gz` (manifest.json, the `marquee/` package, requirements.txt,
optionally wheels/) and `payload.sig`, an Ed25519 signature over the payload
bytes. The same file serves both delivery paths: the device downloads it from
GitHub Releases, or the user downloads it themselves and uploads it on the
settings page. Everything after the signature check is one code path.

Install layout: /opt/marquee/marquee is a symlink into
/opt/marquee/versions/<version>/marquee. The applier unpacks the new version
beside the old one, flips the symlink, restarts the service, and watches it:
if the service is not healthy shortly after, the symlink is flipped back and
the old version restarted. Config in /var/lib/marquee is untouched throughout.

The applier runs detached (systemd-run) because it restarts the very service
the request came in on:

    /opt/marquee/venv/bin/python -m marquee.update apply <file>

Trust model: the public key below is the entire security boundary. Bundles
are accepted only with a valid signature and a version strictly newer than
the running one — an old signed bundle must not be able to reintroduce a
fixed bug (the web API has no downgrade path; the CLI needs --force).
"""

import io
import json
import logging
import os
import random
import re
import shutil
import subprocess
import sys
import tarfile
import threading
import time

log = logging.getLogger(__name__)

PRODUCT = "marquee"
BUNDLE_EXT = ".mqup"

# GitHub repository the checker polls ("owner/repo"). Empty disables the
# check with a clear message rather than a mystery 404. Set at first release.
UPDATE_REPO = ""

# Ed25519 public key (hex). The private half lives only on the maintainer's
# machine (~/.config/marquee-release/signing.key) — never in this repo, never
# in CI. Generated by release/build.py --keygen.
PUBLIC_KEY_HEX = "70fe2a6171919942b18fb4ca352183b00abc34d72e1e51ba93492c6d0f3b9aef"

APP_ROOT = os.environ.get("MARQUEE_APP_ROOT", "/opt/marquee")
VERSIONS_DIR = os.path.join(APP_ROOT, "versions")
PACKAGE_LINK = os.path.join(APP_ROOT, PRODUCT)
# requirements.txt of whatever is currently installed; the applier only runs
# pip when an update actually changes it.
INSTALLED_REQS = os.path.join(APP_ROOT, "requirements.txt")
VENV_PIP = os.path.join(APP_ROOT, "venv", "bin", "pip")
SERVICE = "marquee.service"

STATE_DIR = os.environ.get("MARQUEE_UPDATE_DIR", "/var/lib/marquee/updates")
PENDING = os.path.join(STATE_DIR, "pending" + BUNDLE_EXT)
RESULT_PATH = os.path.join(STATE_DIR, "last_result.json")

# A bundle is the package plus, at most, some wheels.
MAX_BUNDLE_BYTES = 256 * 1024 * 1024

CHECK_INTERVAL_S = 24 * 3600
# Auto-install (opt-in) applies a downloaded update in this local-time window,
# when the panel is at its least missed.
AUTO_INSTALL_HOURS = range(3, 5)


class UpdateError(Exception):
    """A bundle or update step that must be reported, not raised as a bug."""


# ─────────────────────────────────────────────────────────────────────────────
# Versions
# ─────────────────────────────────────────────────────────────────────────────
def parse_version(s: str) -> tuple:
    """'v1.2.3' or '1.2.3' → (1, 2, 3). Raises ValueError otherwise."""
    parts = str(s).strip().lstrip("vV").split(".")
    if not parts or not all(p.isdigit() for p in parts):
        raise ValueError(f"not a version: {s!r}")
    return tuple(int(p) for p in parts)


def is_newer(candidate: str, current: str) -> bool:
    return parse_version(candidate) > parse_version(current)


def current_version() -> str:
    import marquee
    return marquee.__version__


# ─────────────────────────────────────────────────────────────────────────────
# Bundle verification
# ─────────────────────────────────────────────────────────────────────────────
def _read_member(tar: tarfile.TarFile, name: str, limit: int) -> bytes:
    try:
        info = tar.getmember(name)
    except KeyError:
        raise UpdateError(f"not a Marquee update file (missing {name})") from None
    if not info.isfile() or info.size > limit:
        raise UpdateError(f"not a Marquee update file (bad {name})")
    return tar.extractfile(info).read()


def _payload_and_sig(path: str) -> tuple:
    try:
        with tarfile.open(path, "r:") as tar:
            payload = _read_member(tar, "payload.tar.gz", MAX_BUNDLE_BYTES)
            sig = _read_member(tar, "payload.sig", 256)
    except tarfile.TarError as e:
        raise UpdateError(f"not a Marquee update file ({e})") from None
    return payload, sig


def verify_bundle(path: str, pubkey_hex: str = None) -> dict:
    """Signature-check `path` and return its manifest. UpdateError if invalid.

    Nothing from the file is trusted before this returns: the payload is only
    parsed after the signature over its raw bytes has checked out.
    """
    # Imported here so a missing cryptography wheel degrades to "updates
    # unavailable" instead of taking the whole web UI down at import time.
    from cryptography.exceptions import InvalidSignature
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

    payload, sig = _payload_and_sig(path)
    key = Ed25519PublicKey.from_public_bytes(
        bytes.fromhex(pubkey_hex or PUBLIC_KEY_HEX))
    try:
        key.verify(sig, payload)
    except InvalidSignature:
        raise UpdateError(
            "this file is not a genuine Marquee update (signature check "
            "failed)") from None

    try:
        with tarfile.open(fileobj=io.BytesIO(payload), mode="r:gz") as tar:
            manifest = json.loads(_read_member(tar, "manifest.json", 65536))
            names = tar.getnames()
    except (tarfile.TarError, ValueError) as e:
        raise UpdateError(f"update payload is corrupt ({e})") from None

    if manifest.get("product") != PRODUCT:
        raise UpdateError("this update is for a different product")
    try:
        parse_version(manifest.get("version", ""))
    except ValueError:
        raise UpdateError("update has no usable version number") from None
    for n in names:
        top = n.split("/", 1)[0]
        if top not in ("manifest.json", "requirements.txt", PRODUCT, "wheels"):
            raise UpdateError(f"update contains an unexpected file: {n}")
    return manifest


def _extract_payload(path: str, dest: str):
    payload, _ = _payload_and_sig(path)
    with tarfile.open(fileobj=io.BytesIO(payload), mode="r:gz") as tar:
        # The data filter refuses absolute paths, "..", links, and devices.
        tar.extractall(dest, filter="data")


# ─────────────────────────────────────────────────────────────────────────────
# Last-result file (read by the web UI after the service comes back)
# ─────────────────────────────────────────────────────────────────────────────
def write_result(status: str, from_v: str = "", to_v: str = "", error: str = ""):
    os.makedirs(STATE_DIR, exist_ok=True)
    doc = {"status": status, "from": from_v, "to": to_v,
           "error": error, "time": time.time()}
    tmp = RESULT_PATH + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(doc, f)
    os.replace(tmp, RESULT_PATH)


def read_result() -> dict:
    try:
        with open(RESULT_PATH, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}


def schedule_apply(pending: str = PENDING):
    """Run the applier detached. The caller is inside the service the applier
    will restart, so — like factory reset — this only schedules it."""
    subprocess.Popen(
        ["systemd-run", "--collect", "--on-active=2",
         f"--unit=mq-update-{int(time.time())}",
         "-p", f"WorkingDirectory={APP_ROOT}",
         sys.executable, "-m", "marquee.update", "apply", pending])


# ─────────────────────────────────────────────────────────────────────────────
# Applier (runs detached, as root, outside the service)
# ─────────────────────────────────────────────────────────────────────────────
def _systemctl_show(*props) -> dict:
    out = subprocess.run(
        ["systemctl", "show", SERVICE, "-p", ",".join(props)],
        capture_output=True, text=True).stdout
    return dict(line.split("=", 1) for line in out.splitlines() if "=" in line)


def _journal_tail(lines: int = 12) -> str:
    out = subprocess.run(
        ["journalctl", "-u", SERVICE, "-n", str(lines), "--no-pager", "-o", "cat"],
        capture_output=True, text=True).stdout
    return out[-1500:]


def _service_healthy(startup_wait: float = 6, settle: float = 12) -> bool:
    """True if the service starts and *stays* up. `systemctl restart` resets
    NRestarts, so any nonzero value here is a post-update crash."""
    time.sleep(startup_wait)
    st = _systemctl_show("ActiveState", "NRestarts")
    if st.get("ActiveState") != "active":
        return False
    time.sleep(settle)
    st = _systemctl_show("ActiveState", "NRestarts")
    return st.get("ActiveState") == "active" and st.get("NRestarts") == "0"


def _flip_link(target_version: str):
    """Atomically point /opt/marquee/marquee at a version dir. Relative, so
    the tree can be copied or backed up without breaking it."""
    rel = os.path.join("versions", target_version, PRODUCT)
    tmp = PACKAGE_LINK + ".new"
    if os.path.lexists(tmp):
        os.unlink(tmp)
    os.symlink(rel, tmp)
    os.replace(tmp, PACKAGE_LINK)


def _link_version() -> str:
    """Which versions/<v> the package symlink currently points into."""
    target = os.readlink(PACKAGE_LINK)
    parts = os.path.normpath(target).split(os.sep)
    return parts[parts.index("versions") + 1]


def ensure_versioned_layout(current_v: str):
    """First run after the pre-update era: the package is a real directory.
    Move it into versions/<current>/ and leave a symlink in its place."""
    if os.path.islink(PACKAGE_LINK):
        return
    vdir = os.path.join(VERSIONS_DIR, current_v)
    os.makedirs(vdir, exist_ok=True)
    dest = os.path.join(vdir, PRODUCT)
    if os.path.exists(dest):
        shutil.rmtree(dest)
    shutil.move(PACKAGE_LINK, dest)
    _flip_link(current_v)


def _packaged_version(vdir: str) -> str:
    """Read __version__ from an unpacked tree without importing it."""
    with open(os.path.join(vdir, PRODUCT, "__init__.py"), encoding="utf-8") as f:
        m = re.search(r'__version__\s*=\s*"([^"]+)"', f.read())
    if not m:
        raise UpdateError("unpacked update has no __version__")
    return m.group(1)


def _pip_install(vdir: str) -> None:
    """Install the new version's requirements, offline first if it carries
    wheels. Runs before the symlink flip: a failure here aborts the update
    with the old version still installed and running."""
    new_req = os.path.join(vdir, "requirements.txt")
    try:
        with open(new_req, "rb") as f_new, open(INSTALLED_REQS, "rb") as f_cur:
            if f_new.read() == f_cur.read():
                return
    except OSError:
        pass  # unknown current state — install to be safe
    wheels = os.path.join(vdir, "wheels")
    base = [VENV_PIP, "install", "-q", "-r", new_req]
    attempts = [base]
    if os.path.isdir(wheels):
        attempts.insert(0, [VENV_PIP, "install", "-q", "--no-index",
                            "--find-links", wheels, "-r", new_req])
    err = ""
    for cmd in attempts:
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode == 0:
            return
        err = res.stderr[-800:]
    raise UpdateError(f"could not install dependencies: {err}")


def _prune_versions(keep: set):
    keep = set(keep) | {"dev"}   # dev is the deploy.sh target, never pruned
    try:
        entries = os.listdir(VERSIONS_DIR)
    except OSError:
        return
    for name in entries:
        if name not in keep and not name.startswith("."):
            shutil.rmtree(os.path.join(VERSIONS_DIR, name), ignore_errors=True)


def apply_bundle(path: str, force: bool = False) -> int:
    """The whole install: verify → unpack → deps → flip → restart → watch.
    Returns a process exit code; every outcome is also written to the result
    file, because the browser that asked for this was disconnected the moment
    the service restarted."""
    current_v = current_version()
    new_v = ""
    try:
        manifest = verify_bundle(path)
        new_v = manifest["version"]
        if not force and not is_newer(new_v, current_v):
            raise UpdateError(
                f"update {new_v} is not newer than the installed {current_v} "
                "— downgrades are not allowed")

        ensure_versioned_layout(current_v)
        staging = os.path.join(VERSIONS_DIR, ".staging")
        shutil.rmtree(staging, ignore_errors=True)
        os.makedirs(staging)
        _extract_payload(path, staging)
        packaged = _packaged_version(staging)
        if packaged != new_v:
            raise UpdateError(
                f"manifest says {new_v} but the code inside says {packaged}")

        vdir = os.path.join(VERSIONS_DIR, new_v)
        shutil.rmtree(vdir, ignore_errors=True)
        os.replace(staging, vdir)
        _pip_install(vdir)
    except UpdateError as e:
        log.error("Update failed before install: %s", e)
        write_result("failed", current_v, new_v, str(e))
        return 1

    prev = _link_version()
    write_result("installing", current_v, new_v)
    log.info("Installing %s (was %s)", new_v, current_v)
    _flip_link(new_v)
    subprocess.run(["systemctl", "restart", SERVICE])

    if _service_healthy():
        try:
            shutil.copyfile(os.path.join(vdir, "requirements.txt"), INSTALLED_REQS)
        except OSError:
            pass
        try:
            os.unlink(path)
        except OSError:
            pass
        _prune_versions({new_v, prev})
        write_result("updated", current_v, new_v)
        log.info("Update to %s healthy", new_v)
        return 0

    # The new version did not stay up — put the old one back.
    tail = _journal_tail()
    log.error("Update to %s unhealthy — rolling back to %s", new_v, prev)
    _flip_link(prev)
    subprocess.run(["systemctl", "restart", SERVICE])
    write_result("rolled_back", current_v, new_v,
                 f"the new version did not start, so {current_v} was "
                 f"restored. Log excerpt:\n{tail}")
    return 1


# ─────────────────────────────────────────────────────────────────────────────
# Update checker (thread inside the service)
# ─────────────────────────────────────────────────────────────────────────────
class Updater:
    """Owns everything update-shaped the web UI needs: the daily GitHub
    check, the downloaded/uploaded pending bundle, and the opt-in overnight
    auto-install. All network work happens on this thread or in a web
    request; the render loop never sees any of it."""

    def __init__(self, config, stop: threading.Event):
        self.config = config
        self.stop = stop
        self.lock = threading.Lock()
        self.available = None          # {"version", "url", "notes"} or None
        self.check_error = ""
        self.last_check = 0.0

    def start(self):
        threading.Thread(target=self._loop, daemon=True, name="updater").start()

    def _loop(self):
        # Let the network come up first; jitter so a fleet on one LAN does
        # not hit the API in lockstep after a power cut.
        self.stop.wait(60 + random.uniform(0, 120))
        while not self.stop.is_set():
            cfg = self.config.get()["updates"]
            if cfg["auto_check"] and time.time() - self.last_check >= CHECK_INTERVAL_S:
                self.check_now()
            if cfg["auto_install"]:
                self._maybe_auto_install()
            self.stop.wait(300 + random.uniform(0, 60))

    def check_now(self) -> dict:
        """Poll GitHub's latest release. Safe to call from a web request."""
        import requests
        self.last_check = time.time()
        if not UPDATE_REPO:
            with self.lock:
                self.available, self.check_error = None, ""
            return self.status()
        try:
            r = requests.get(
                f"https://api.github.com/repos/{UPDATE_REPO}/releases/latest",
                headers={"Accept": "application/vnd.github+json",
                         "User-Agent": f"{PRODUCT}/{current_version()}"},
                timeout=10)
            r.raise_for_status()
            rel = r.json()
            tag = rel.get("tag_name", "")
            asset = next((a for a in rel.get("assets", [])
                          if a.get("name", "").endswith(BUNDLE_EXT)), None)
            found = None
            try:
                newer = bool(asset) and is_newer(tag, current_version())
            except ValueError:
                newer = False   # a tag like "beta" is not an update offer
            if newer:
                found = {"version": tag.strip().lstrip("vV"),
                         "url": asset["browser_download_url"],
                         "notes": (rel.get("body") or "")[:2000]}
            with self.lock:
                self.available, self.check_error = found, ""
        except Exception as e:
            log.warning("Update check failed: %s", e)
            with self.lock:
                self.check_error = f"could not check for updates: {e}"
        return self.status()

    def download_pending(self) -> dict:
        """Fetch the available release bundle and verify it. Returns its
        manifest; leaves the verified file at PENDING for apply."""
        import requests
        with self.lock:
            avail = dict(self.available) if self.available else None
        if not avail:
            raise UpdateError("no update available to download")
        os.makedirs(STATE_DIR, exist_ok=True)
        tmp = PENDING + ".part"
        try:
            with requests.get(avail["url"], stream=True, timeout=30) as r:
                r.raise_for_status()
                size = 0
                with open(tmp, "wb") as f:
                    for chunk in r.iter_content(1024 * 256):
                        size += len(chunk)
                        if size > MAX_BUNDLE_BYTES:
                            raise UpdateError("update file is implausibly large")
                        f.write(chunk)
        except UpdateError:
            raise
        except Exception as e:
            raise UpdateError(f"download failed: {e}") from None
        manifest = verify_bundle(tmp)   # raises before anything is kept
        os.replace(tmp, PENDING)
        return manifest

    def _maybe_auto_install(self):
        if time.localtime().hour not in AUTO_INSTALL_HOURS:
            return
        with self.lock:
            avail = dict(self.available) if self.available else None
        if not avail:
            return
        # One attempt per version: a rollback or failure recorded for this
        # version means a human needs to look, not that 3am should retry it
        # nightly forever.
        last = read_result()
        if last.get("to") == avail["version"]:
            return
        try:
            self.download_pending()
            log.info("Auto-installing update %s", avail["version"])
            schedule_apply()
        except UpdateError as e:
            log.warning("Auto-install skipped: %s", e)
            write_result("failed", current_version(), avail["version"], str(e))

    def status(self) -> dict:
        with self.lock:
            avail = dict(self.available) if self.available else None
            err = self.check_error
        return {
            "current": current_version(),
            "available": avail,
            "check_error": err,
            "last_check": self.last_check,
            "last_result": read_result(),
            "pending": os.path.exists(PENDING),
        }


# ─────────────────────────────────────────────────────────────────────────────
# CLI (the detached applier; also handy over SSH)
# ─────────────────────────────────────────────────────────────────────────────
def main(argv=None) -> int:
    import argparse
    logging.basicConfig(level="INFO", format="%(asctime)s %(levelname)s %(message)s")
    p = argparse.ArgumentParser(prog="marquee.update")
    sub = p.add_subparsers(dest="cmd", required=True)
    ap = sub.add_parser("apply", help="verify and install a bundle")
    ap.add_argument("file")
    ap.add_argument("--force", action="store_true",
                    help="allow reinstalling the same or an older version")
    vp = sub.add_parser("verify", help="signature-check a bundle and print its manifest")
    vp.add_argument("file")
    args = p.parse_args(argv)

    if args.cmd == "verify":
        try:
            print(json.dumps(verify_bundle(args.file), indent=2))
            return 0
        except UpdateError as e:
            print(f"INVALID: {e}", file=sys.stderr)
            return 1
    return apply_bundle(args.file, force=args.force)


if __name__ == "__main__":
    sys.exit(main())
